import { DataSource } from 'typeorm';
import { User } from '../../app/entities/user.entity';
import * as bcrypt from 'bcrypt';

export async function seedUsers(dataSource: DataSource) {
  const userRepository = dataSource.getRepository(User);

  // Check if seed users already exist
  const adminExists = await userRepository.findOne({
    where: { email: 'admin@wishzy.com' },
  });

  if (adminExists) {
    console.log('Seed users already exist, skipping...');
    return;
  }

  const hashedPassword = await bcrypt.hash('Password@123', 10);

  const users = [
    // Admin users
    {
      email: 'admin@wishzy.com',
      fullName: 'Admin Master',
      password: hashedPassword,
      role: 'admin',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234567',
      gender: 'male',
      age: 35,
      address: 'Ho Chi Minh City, Vietnam',
    },
    {
      email: 'admin2@wishzy.com',
      fullName: 'Sarah Admin',
      password: hashedPassword,
      role: 'admin',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234568',
      gender: 'female',
      age: 32,
      address: 'Hanoi, Vietnam',
    },

    // Instructor users
    {
      email: 'instructor1@wishzy.com',
      fullName: 'John Instructor',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: true,
      phone: '0901234569',
      gender: 'male',
      age: 40,
      address: 'Da Nang, Vietnam',
    },
    {
      email: 'instructor2@wishzy.com',
      fullName: 'Emily Teacher',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: true,
      phone: '0901234570',
      gender: 'female',
      age: 38,
      address: 'Can Tho, Vietnam',
    },
    {
      email: 'instructor3@wishzy.com',
      fullName: 'Michael Brown',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: true,
      phone: '0901234571',
      gender: 'male',
      age: 45,
      address: 'Hai Phong, Vietnam',
    },
    {
      email: 'instructor4@wishzy.com',
      fullName: 'Lisa Anderson',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'google',
      isInstructorActive: true,
      phone: '0901234572',
      gender: 'female',
      age: 36,
      address: 'Nha Trang, Vietnam',
    },
    {
      email: 'instructor5@wishzy.com',
      fullName: 'David Wilson',
      password: hashedPassword,
      role: 'instructor',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234573',
      gender: 'male',
      age: 42,
      address: 'Hue, Vietnam',
    },

    // Regular users
    {
      email: 'user1@wishzy.com',
      fullName: 'Nguyen Van A',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234574',
      gender: 'male',
      age: 25,
      address: 'District 1, Ho Chi Minh City',
    },
    {
      email: 'user2@wishzy.com',
      fullName: 'Tran Thi B',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234575',
      gender: 'female',
      age: 23,
      address: 'District 3, Ho Chi Minh City',
    },
    {
      email: 'user3@wishzy.com',
      fullName: 'Le Van C',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234576',
      gender: 'male',
      age: 28,
      address: 'Tan Binh, Ho Chi Minh City',
    },
    {
      email: 'user4@wishzy.com',
      fullName: 'Pham Thi D',
      password: hashedPassword,
      role: 'user',
      verified: false,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234577',
      gender: 'female',
      age: 22,
      address: 'District 7, Ho Chi Minh City',
    },
    {
      email: 'user5@wishzy.com',
      fullName: 'Hoang Van E',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234578',
      gender: 'male',
      age: 30,
      address: 'Binh Thanh, Ho Chi Minh City',
    },
    {
      email: 'user6@wishzy.com',
      fullName: 'Vo Thi F',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234579',
      gender: 'female',
      age: 26,
      address: 'Phu Nhuan, Ho Chi Minh City',
    },
    {
      email: 'user7@wishzy.com',
      fullName: 'Dang Van G',
      password: hashedPassword,
      role: 'user',
      verified: false,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234580',
      gender: 'male',
      age: 24,
      address: 'Go Vap, Ho Chi Minh City',
    },
    {
      email: 'user8@wishzy.com',
      fullName: 'Bui Thi H',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234581',
      gender: 'female',
      age: 27,
      address: 'District 10, Ho Chi Minh City',
    },
    {
      email: 'user9@wishzy.com',
      fullName: 'Do Van I',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234582',
      gender: 'male',
      age: 29,
      address: 'Thu Duc, Ho Chi Minh City',
    },
    {
      email: 'user10@wishzy.com',
      fullName: 'Ngo Thi K',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234583',
      gender: 'female',
      age: 21,
      address: 'District 2, Ho Chi Minh City',
    },
    {
      email: 'user11@wishzy.com',
      fullName: 'Truong Van L',
      password: hashedPassword,
      role: 'user',
      verified: false,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234584',
      gender: 'male',
      age: 31,
      address: 'District 4, Ho Chi Minh City',
    },
    {
      email: 'user12@wishzy.com',
      fullName: 'Duong Thi M',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234585',
      gender: 'female',
      age: 25,
      address: 'District 5, Ho Chi Minh City',
    },
    {
      email: 'user13@wishzy.com',
      fullName: 'Ly Van N',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234586',
      gender: 'male',
      age: 33,
      address: 'District 6, Ho Chi Minh City',
    },
    {
      email: 'user14@wishzy.com',
      fullName: 'Mac Thi O',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234587',
      gender: 'female',
      age: 28,
      address: 'District 8, Ho Chi Minh City',
    },
    {
      email: 'user15@wishzy.com',
      fullName: 'Dinh Van P',
      password: hashedPassword,
      role: 'user',
      verified: false,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234588',
      gender: 'male',
      age: 26,
      address: 'District 11, Ho Chi Minh City',
    },
    {
      email: 'user16@wishzy.com',
      fullName: 'Ha Thi Q',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234589',
      gender: 'female',
      age: 24,
      address: 'District 12, Ho Chi Minh City',
    },
    {
      email: 'user17@wishzy.com',
      fullName: 'Cao Van R',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234590',
      gender: 'male',
      age: 27,
      address: 'Binh Tan, Ho Chi Minh City',
    },
    {
      email: 'user18@wishzy.com',
      fullName: 'Tang Thi S',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234591',
      gender: 'female',
      age: 29,
      address: 'Tan Phu, Ho Chi Minh City',
    },
    {
      email: 'user19@wishzy.com',
      fullName: 'Lam Van T',
      password: hashedPassword,
      role: 'user',
      verified: false,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234592',
      gender: 'male',
      age: 32,
      address: 'Cu Chi, Ho Chi Minh City',
    },
    {
      email: 'user20@wishzy.com',
      fullName: 'Vu Thi U',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'google',
      isInstructorActive: false,
      phone: '0901234593',
      gender: 'female',
      age: 23,
      address: 'Hoc Mon, Ho Chi Minh City',
    },
    {
      email: 'user21@wishzy.com',
      fullName: 'Quach Van V',
      password: hashedPassword,
      role: 'user',
      verified: true,
      loginType: 'local',
      isInstructorActive: false,
      phone: '0901234594',
      gender: 'male',
      age: 30,
      address: 'Nha Be, Ho Chi Minh City',
    },
  ];

  // Insert directly to bypass @BeforeInsert hook (password already hashed)
  await userRepository
    .createQueryBuilder()
    .insert()
    .into(User)
    .values(users as any)
    .execute();

  console.log(`✅ Successfully seeded ${users.length} users!`);
}
